### ISSUE TITLE
[Request] Darwin docker image in registry

### ISSUE THREAD

**Issue by RafayGhafoor** [openfaas/classic-watchdog#13]
Can we please have [Darwin/arm64 image](https://github.com/openfaas/classic-watchdog/pkgs/container/classic-watchdog/146303368?tag=b20362a05bde813764e0b20d27de58df2159bc0a) as well as the arm64 image currently provided doesn't work on M1 Silicon and gives exec format error?

![2023-11-15 at 02 28 44](https://github.com/openfaas/classic-watchdog/assets/20343475/4d4252b0-5879-464b-8ea3-68c3f409dce5)

**Comment by alexellis** [comment]
Hi @RafayGhafoor 

Why are you running the watchdog on your own machine and not in a container?

Alex
